name: Deploy Node Application 

on: 
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t lepakshia/updated-reactjs-frontend --build-arg REACT-APP-BASEURL='production' --build-arg BACKEND_URL=${{ secrets.BACKEND_URL }} .  
      - name: Publish Image to docker hub
        run: docker push lepakshia/updated-reactjs-frontend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull lepakshia/updated-reactjs-frontend:latest
      - name: Delete old container
        run: sudo docker rm -f reactjs-frontend-container  
      - name: Run Docker Container
        run: sudo docker run -d -p 3000:80 --name reactjs-frontend-container lepakshia/updated-reactjs-frontend
